name: Shell Commands2

#on: [push, pull_request] #PR追記
on:
  push:
  pull_request:
    type:[closed,assigned,opend,reopend] #さらにtypeを指定できる

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!!!!!!!"
      - name: multi script
        run: |
          node -v
          npm -v
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"] #jobsをparallelではなくseriesで実行するために,arrayで依存関係書く
    steps:
      - name: Directory PowerShell
        run: Get-location
      - name: Directory Bash
        run: pwd
        shell: bash

  run-javascript-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: James
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"


  run-checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
